import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AppProvider } from "@/lib/AppContext";
import { Loading } from "@/components/Loader";

export const metadata: Metadata = {
  title: "CareerHunt",
  description: "Generated by create next app",
};

const font = DM_Sans({
  subsets: ["latin"],
  preload: true,
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={font.className}>
          <Loading />
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </AppProvider>
  );
}
